[project]
name = "pitchdeck_analyzer"
version = "0.0.1"
description = "This is the start of your AgentStack project."
authors = [
    { name = "Name <Email>" }
]
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "agentstack[crewai]>=0.3.0",
]